/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_linkedin_ktls_KernelTLSNativeHelper */

#ifndef _Included_com_linkedin_ktls_KernelTLSNativeHelper
#define _Included_com_linkedin_ktls_KernelTLSNativeHelper
#ifdef __cplusplus
extern "C" {
#endif
#undef com_linkedin_ktls_KernelTLSNativeHelper_UNSUPPORTED_OPERATING_SYSTEM
#define com_linkedin_ktls_KernelTLSNativeHelper_UNSUPPORTED_OPERATING_SYSTEM 6001L
#undef com_linkedin_ktls_KernelTLSNativeHelper_UNSUPPORTED_CIPHER
#define com_linkedin_ktls_KernelTLSNativeHelper_UNSUPPORTED_CIPHER 6002L
#undef com_linkedin_ktls_KernelTLSNativeHelper_UNSUPPORTED_OPERATION
#define com_linkedin_ktls_KernelTLSNativeHelper_UNSUPPORTED_OPERATION 6003L
#undef com_linkedin_ktls_KernelTLSNativeHelper_UNABLE_TO_SET_TLS_MODE
#define com_linkedin_ktls_KernelTLSNativeHelper_UNABLE_TO_SET_TLS_MODE 6004L
#undef com_linkedin_ktls_KernelTLSNativeHelper_UNABLE_TO_SET_TLS_PARAMS
#define com_linkedin_ktls_KernelTLSNativeHelper_UNABLE_TO_SET_TLS_PARAMS 6005L
/*
 * Class:     com_linkedin_ktls_KernelTLSNativeHelper
 * Method:    enableKernelTlsForSend_AES_128_GCM
 * Signature: (II[B[B[B[B)I
 */
JNIEXPORT jint JNICALL Java_com_linkedin_ktls_KernelTLSNativeHelper_enableKernelTlsForSend_1AES_1128_1GCM
  (JNIEnv *, jobject, jint, jint, jbyteArray, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     com_linkedin_ktls_KernelTLSNativeHelper
 * Method:    enableKernelTlsForSend_AES_256_GCM
 * Signature: (II[B[B[B[B)I
 */
JNIEXPORT jint JNICALL Java_com_linkedin_ktls_KernelTLSNativeHelper_enableKernelTlsForSend_1AES_1256_1GCM
  (JNIEnv *, jobject, jint, jint, jbyteArray, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     com_linkedin_ktls_KernelTLSNativeHelper
 * Method:    enableKernelTlsForSend_CHACHA20_POLY1305
 * Signature: (II[B[B[B[B)I
 */
JNIEXPORT jint JNICALL Java_com_linkedin_ktls_KernelTLSNativeHelper_enableKernelTlsForSend_1CHACHA20_1POLY1305
  (JNIEnv *, jobject, jint, jint, jbyteArray, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     com_linkedin_ktls_KernelTLSNativeHelper
 * Method:    disableKernelTls
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_linkedin_ktls_KernelTLSNativeHelper_disableKernelTls
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
