name: Release build on tags

# Run this workflow every time a tag is created/pushed
on:
  push:
    tags:
      - '*'

jobs:
  publish:
    # Name the Job
    name: Build tagged commit and upload the artifacts
    # Set the type of machine to run on
    runs-on: ubuntu-latest
    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          # bring in all history because the gradle versions plugin needs to "walk back" to the closest ancestor tag
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Set up release version env variable
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Print the release version
        run: |
          echo "Release version (tag name): ${{ env.RELEASE_VERSION }}"
      - name: Build and publish
        env:
          JFROG_USERNAME: ${{ secrets.JFROG_USERNAME }}
          JFROG_API_KEY: ${{ secrets.JFROG_API_KEY }}
        # Maintain lexicographical order for subprojects
        run: |
          ./gradlew -PbuildType=docker -Pversion=${{ env.RELEASE_VERSION }} :clients:publish :core:publish :metadata:publish :raft:publish :server-common:publish :storage:publish :storage:api:publish --no-daemon
